const WIDTH = 100
const HEIGHT = 65;
const MIN_HEIGHT = 35;

const MIN_ROWS = 7

const HEIGHT_REDUCTION_CONCURRENT = 5;

export {
    WIDTH,
    HEIGHT,
    MIN_HEIGHT,
    HEIGHT_REDUCTION_CONCURRENT,
    MIN_ROWS
}